global:
  scrape_interval: 15s

rule_files:
  - "alerts.yaml"

scrape_configs:
  - job_name: "ai-log-anomaly-detection"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093