apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-log-anomaly-detection-custom
  namespace: ai-log-anomaly
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-log-anomaly-detection
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Pods
      pods:
        metric:
          name: app_requests_per_second
        target:
          type: AverageValue
          averageValue: "5"