apiVersion: v1
kind: Service
metadata:
  name: ai-log-anomaly-detection
  namespace: ai-log-anomaly
spec:
  selector:
    app: ai-log-anomaly-detection
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP